name = "astro-endonautas"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "endonautas-mensajes"
database_id = "7061d3e5-fa96-4a12-a684-2164246c1803"
